spring:
  datasource:
    server1:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/server?serverTimezone=Asia/Seoul&useSSL=false
      username: root
      password: 1234
    batch:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/batch?serverTimezone=Asia/Seoul&useSSL=false
      username: root
      password: 1234

  batch:
    jdbc:
      initialize-schema: always
    job:
      name: job
      enabled: true

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  jms:
    template:
      default-destination: customers
      receive-timeout: 5000
  activemq:
    broker-url: vm://localhost?broker.persistent=false
    packages:
      trust-all: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: woonie155
    password: 1 #앱번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
