spring:
  datasource:
    server1:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/server?serverTimezone=Asia/Seoul&useSSL=false
      username: root
      password: 1234
    batch:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/batch?serverTimezone=Asia/Seoul&useSSL=false
      username: root
      password: 1234

  batch:
    jdbc:
      initialize-schema: always
    job:
      name: JobExplorerJob
      enabled: false
